# -*- coding: utf-8 -*-
"""streamLit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TvamTRe9vYN4UYX01NjXBfVGWB19mlB1
"""



import streamlit as st

# Title of the application
st.title('Find the Largest Number')

# Input fields for the numbers
number1 = st.number_input('Enter first number', format='%f')
number2 = st.number_input('Enter second number', format='%f')
number3 = st.number_input('Enter third number', format='%f')

# Button to perform the action
if st.button('Find the Largest Number'):
    # Find the largest number
    largest = max(number1, number2, number3)
    # Display the largest number
    st.write(f'The largest number is {largest}')